### ISSUE TITLE
Dedicated Server crash when player tries to use Better End sign as a sign shop

### ISSUE THREAD

**Issue by dandin87** [Gunpowder-MC/GunpowderSignshop#2]
AoF 2.5.9 NA Server.

https://paste.lucko.me/8HGIpPwUSc

Description: Ticking entity
java.lang.ClassCastException: ru.betterend.blocks.entities.ESignBlockEntity cannot be cast to net.minecraft.block.entity.SignBlockEntity
    at io.github.gunpowder.entities.GunpowderEvents$init$1.trigger(GunpowderEvents.java:46)
    at net.minecraft.server.network.ServerPlayerInteractionManager.handler$zdp000$breakCallback(ServerPlayerInteractionManager.java:1049)
    at net.minecraft.server.network.ServerPlayerInteractionManager.tryBreakBlock(ServerPlayerInteractionManager.java:248)
    at net.minecraft.server.network.ServerPlayerInteractionManager.update(ServerPlayerInteractionManager.java:103)
    at net.minecraft.server.network.ServerPlayerEntity.tick(ServerPlayerEntity.java:379)
    at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld.java:621)
    at net.minecraft.world.World.tickEntity(World.java:561)

**Comment by Martmists-GH** [comment]
This issue exists because BetterEnd's ESignBlockEntity does not extend Minecraft's SignBlockEntity. I've opened an issue [here](https://github.com/paulevsGitch/BetterEnd/issues/82) to track it, but this is not a bug on our end.
